cluster:
  managed: true
  storageClasses:
    local: k8s-local-storage
    managed: ceph-corbo-cephfs
global:
  publicHost: hbpmip.link
engines:
  exaflow:
    url: "http://exaflow-controller-service:5000"
mip:
  version: 9.0.4
platform-ui:
  image:
    repository: hbpmip/platform-ui
    tag: 1.1.0
  ingress:
    enabled: true
    className: haproxy-public
    certManagerClusterIssuer: letsencrypt-public
    tlsSecretName: platform-ui-tls
  backend:
    host: platform-backend-service
    port: 8080
    context: services
  guide:
    covariate: Sex
    variable: Age
platform-backend:
  image:
    repository: hbpmip/platform-backend
    tag: 9.2.1
  config:
    logLevel: INFO
    logLevelFramework: INFO
    algorithmUpdateInterval: 60
  persistence:
    data:
      size: 100Mi
    logs:
      size: 1Gi

platformBackendDatabase:
  image:
    repository: postgres
    tag: 18.3-alpine
  persistence:
    size: 1Gi

keycloak:
  enabled: true
  host: iam.ebrains.eu
