cluster:
  managed: true
  storageClasses:
    local: k8s-local-storage
    managed: ceph-corbo-cephfs
global:
  publicHost: hbpmip.link
engines:
  exaflow:
    url: "http://exaflow-controller-service:5000"
mip:
  version: 9.0.3
platform-ui:
  image:
    repository: hbpmip/platform-ui
    tag: 1.0.2
  service:
    nodePort: 30080
  ingress:
    enabled: true
    className: haproxy-public
    certManagerClusterIssuer: letsencrypt-public
    tlsSecretName: platform-ui-tls
    redirectRootTo: ''
  backend:
    host: platform-backend-service
    port: 8080
    context: services
platform-backend:
  image:
    repository: hbpmip/platform-backend
    tag: 9.1.2
  config:
    logLevel: INFO
    logLevelFramework: INFO
    algorithmUpdateInterval: 60
  persistence:
    data:
      localPath: /opt/mip-deployment/config
      size: 100Mi
    logs:
      localPath: /opt/mip-deployment/logs
      size: 1Gi

platformBackendDatabase:
  image:
    repository: postgres
    tag: 18.3-alpine
  persistence:
    localPath: /opt/mip-deployment/.stored_data/platform_backenddb
    size: 1Gi

keycloak:
  enabled: true
  host: iam.ebrains.eu
